{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    app: {{ include "frontend.name" . }}
    chart: {{ include "frontend.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "frontend.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "frontend.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
