{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      serviceAccountName: {{ include "backend.fullname" . }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-app-config
            {{- if .Values.secrets.enabled }}
            - secretRef:
                name: {{ .Values.secrets.name }}
            {{- end }}

          
          env:
            {{- if .Values.externalMongo.enabled }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externalMongo.passwordSecret.name }}
                  key: {{ .Values.externalMongo.passwordSecret.key }}
            {{- end }}


          livenessProbe:
            httpGet:
              path: {{ .Values.health.livenessPath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.health.livenessInitialDelay }}
            periodSeconds: {{ .Values.health.livenessPeriod }}
            timeoutSeconds: {{ .Values.health.timeout }}
            failureThreshold: {{ .Values.health.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.health.readinessPath }}
              port: {{ .Values.containerPort }}
            initialDelaySeconds: {{ .Values.health.readinessInitialDelay }}
            periodSeconds: {{ .Values.health.readinessPeriod }}
            timeoutSeconds: {{ .Values.health.timeout }}
            failureThreshold: {{ .Values.health.failureThreshold }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}